name: WoodCutter
main: se.enji.WoodCutter
author: enjikaka
website: http://enji.se
version: 1.4.1

permissions:
  woodcutter.use:
    description: Give you access to use WoodCutters features.
    default: op
