name: WoodCutter
main: se.enji.WoodCutter
author: enjikaka
website: http://labs.enji.se/mc/WoodCutter
version: 1.4.6

permissions:
  woodcutter.use:
    description: Give you access to use WoodCutters features.
    default: op
