name: WoodCutter
main: se.enji.WoodCutter
author: enjikaka
website: http://minecraft.jeremy.se/WoodCutter
version: 1.4.8

permissions:
  woodcutter.use:
    description: Give you access to use WoodCutters features.
    default: op
