name: WoodCutter16
main: pl.andus.WoodCutter
authors: [enjikaka, RoyCurtis, Andus]
website: http://minecraft.jeremy.se/WoodCutter
version: 1.0.0
api-version: 1.16

permissions:
  woodcutter.use:
    description: Give you access to use WoodCutters features.
    default: op
